// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $.backstretch("img/preslawn.png");
    return $(".backstretch").css({
      "position": "absolute"
    });
  });

}).call(this);
