// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $.backstretch("img/preslawn.jpg");
    return $(".backstretch").css({
      "position": "static"
    });
  });

}).call(this);
